[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
num-bigint = "0.4.3"
num-traits = "0.2.14"
itertools = "0.10.3"
nom = "7.1.0"